import type { CitizenProfile } from '@/lib/types';
import { validateCitationSources } from '@/lib/validation/citations';

const digilockerUrl = 'https://www.digilocker.gov.in/';

export const citizenProfiles: CitizenProfile[] = [
  {
    id: 'demo-priya',
    displayName: 'Priya Demo',
    demoPin: '1234',
    identity: {
      aadhaarLast4: '4417',
      name: 'Priya Sharma',
      address: '42 Demo Lane, Sample Nagar, Telangana 500000',
      dob: '14 August 2005',
    },
    issues: [
      {
        id: 'priya-wrong-routing',
        type: 'wrong_routing',
        severity: 'high',
        title: 'Scholarship money is routed to an unused account',
        detail: 'The benefit account was last used in 2022. The current form names a different account.',
        cost: '₹47,000 not received',
        action: { label: 'How to reseed', href: '/records?open=bank' },
        source: { instrument: 'TODO_CITATION' },
      },
      {
        id: 'priya-father-name',
        type: 'mismatch',
        severity: 'high',
        title: "Father's name differs between two records",
        detail: 'The identity record says Rajeev Kumar. The income certificate says Rajiv Kumar.',
        action: { label: 'See the fix', href: '/records?open=income-certificate' },
        source: { instrument: 'P0 prototype document-consistency policy' },
      },
      {
        id: 'priya-unknown-sim',
        type: 'unknown_sim',
        severity: 'medium',
        title: 'A telecom verification is not recognised',
        detail: 'A fictional telecom operator checked the synthetic identity record on 3 August.',
        action: { label: 'Report it' },
        source: { instrument: 'Prototype citizen-report safety rule' },
      },
      {
        id: 'priya-expired-caste',
        type: 'expired',
        severity: 'low',
        title: 'The category certificate has expired',
        detail: 'The synthetic certificate lapsed four months ago.',
        action: { label: 'How to renew', href: '/documents' },
        source: { instrument: 'TODO_CITATION' },
      },
    ],
    records: [
      {
        id: 'income-certificate',
        connectedTo: 'Income certificate',
        detail: 'Father’s name does not match the identity record',
        required: 'required',
        status: 'blocked',
        source: { instrument: 'P0 prototype document-consistency policy' },
        values: [
          { source: 'aadhaar', label: 'Synthetic identity record', value: 'Rajeev Kumar' },
          { source: 'incomeCertificate', label: 'Synthetic income certificate', value: 'Rajiv Kumar' },
        ],
        proposedChange: {
          source: 'incomeCertificate',
          field: 'fatherName',
          newValue: 'Rajeev Kumar',
        },
        action: 'Correct the father’s name on the income certificate.',
      },
      {
        id: 'bank',
        connectedTo: 'Bank benefit routing',
        detail: 'Points to the account last used in 2022',
        required: 'conditional',
        status: 'wrong',
        source: { instrument: 'TODO_CITATION' },
        values: [
          { source: 'bank', label: 'Synthetic bank record', value: 'DEMO-ACCT-2201' },
          { source: 'applicationForm', label: 'Synthetic scholarship form', value: 'DEMO-ACCT-9914' },
        ],
        proposedChange: {
          source: 'applicationForm',
          field: 'bankAccount',
          newValue: 'DEMO-ACCT-2201',
        },
        action: 'Reseed the scholarship form to the current benefit account.',
      },
      {
        id: 'caste-certificate',
        connectedTo: 'Category certificate',
        detail: 'Expired on 27 April 2026',
        required: 'required',
        status: 'expired',
        source: { instrument: 'TODO_CITATION' },
        action: 'Ask the certificate issuer about renewal.',
      },
      {
        id: 'pan',
        connectedTo: 'PAN',
        detail: 'Name matches the synthetic identity record',
        required: 'conditional',
        status: 'clear',
        source: { instrument: 'Prototype consistency check — not a legal requirement' },
        action: 'No correction is suggested.',
      },
      {
        id: 'land',
        connectedTo: 'Land record',
        detail: 'This prototype cannot check the domain',
        required: '—',
        status: 'unknown',
        source: { instrument: 'Prototype unknown-state disclosure rule' },
        action: 'Check directly with the record-owning authority if needed.',
      },
      {
        id: 'voter',
        connectedTo: 'Voter roll',
        detail: 'Not used for this scholarship check',
        required: 'voluntary',
        status: 'optional',
        source: { instrument: 'Prototype data-minimisation rule' },
        action: 'No connection is suggested.',
      },
    ],
    activity: [
      {
        id: 'priya-scholarship',
        agency: 'The fictional scholarship portal',
        when: '12 August 2026',
        purpose: 'Identity and income details',
        recognised: true,
      },
      {
        id: 'priya-telecom',
        agency: 'A fictional telecom operator',
        when: '3 August 2026',
        purpose: 'Identity details',
        recognised: false,
      },
      {
        id: 'priya-bank',
        agency: 'Demo Bank',
        when: '29 July 2026',
        purpose: 'Name and account status',
        recognised: true,
      },
      {
        id: 'priya-wallet',
        agency: 'The local demo wallet',
        when: '18 July 2026',
        purpose: 'Document availability',
        recognised: true,
      },
    ],
    documents: [
      {
        source: 'aadhaar',
        label: 'Synthetic identity record',
        issuer: 'Local demo wallet',
        provenance: 'issued',
        state: 'available',
        issuedOn: '10 January 2024',
        digilockerUrl,
      },
      {
        source: 'marksheet12',
        label: 'Synthetic Class 12 marksheet',
        issuer: 'Demo Education Board',
        provenance: 'issued',
        state: 'available',
        issuedOn: '20 May 2023',
        digilockerUrl,
      },
      {
        source: 'bank',
        label: 'Synthetic bank account proof',
        issuer: 'Demo Bank',
        provenance: 'issued',
        state: 'available',
        issuedOn: '12 June 2022',
        digilockerUrl,
      },
      {
        source: 'incomeCertificate',
        label: 'Synthetic income certificate',
        issuer: 'Demo Revenue Office',
        provenance: 'uploaded',
        state: 'available',
        issuedOn: '1 March 2026',
        validUntil: '28 February 2027',
        digilockerUrl,
      },
      {
        source: 'casteCertificate',
        label: 'Category certificate renewal',
        issuer: 'Demo Revenue Office',
        provenance: 'uploaded',
        state: 'pending',
        issuedOn: 'Applied 20 August 2026',
        digilockerUrl,
      },
    ],
  },
  {
    id: 'demo-arun',
    displayName: 'Arun Demo',
    demoPin: '1234',
    identity: {
      aadhaarLast4: '8032',
      name: 'Arun Rao',
      address: '8 Example Road, Sample Colony, Karnataka 500000',
      dob: '3 November 2004',
    },
    issues: [],
    records: [
      {
        id: 'income-certificate',
        connectedTo: 'Income certificate',
        detail: 'The compared fields match',
        required: 'required',
        status: 'clear',
        source: { instrument: 'P0 prototype document-consistency policy' },
        action: 'No correction is suggested.',
      },
      {
        id: 'bank',
        connectedTo: 'Bank benefit routing',
        detail: 'The form and bank record agree',
        required: 'conditional',
        status: 'clear',
        source: { instrument: 'TODO_CITATION' },
        action: 'No correction is suggested.',
      },
      {
        id: 'caste-certificate',
        connectedTo: 'Category certificate',
        detail: 'Current until 2 January 2030',
        required: 'required',
        status: 'clear',
        source: { instrument: 'TODO_CITATION' },
        action: 'No correction is suggested.',
      },
      {
        id: 'pan',
        connectedTo: 'PAN',
        detail: 'Name matches the synthetic identity record',
        required: 'conditional',
        status: 'clear',
        source: { instrument: 'Prototype consistency check — not a legal requirement' },
        action: 'No correction is suggested.',
      },
      {
        id: 'land',
        connectedTo: 'Land record',
        detail: 'This prototype cannot check the domain',
        required: '—',
        status: 'unknown',
        source: { instrument: 'Prototype unknown-state disclosure rule' },
        action: 'Check directly with the record-owning authority if needed.',
      },
      {
        id: 'voter',
        connectedTo: 'Voter roll',
        detail: 'Not used for this scholarship check',
        required: 'voluntary',
        status: 'optional',
        source: { instrument: 'Prototype data-minimisation rule' },
        action: 'No connection is suggested.',
      },
    ],
    activity: [
      {
        id: 'arun-scholarship',
        agency: 'The fictional scholarship portal',
        when: '11 August 2026',
        purpose: 'Identity and income details',
        recognised: true,
      },
      {
        id: 'arun-bank',
        agency: 'Demo Bank',
        when: '30 July 2026',
        purpose: 'Name and account status',
        recognised: true,
      },
    ],
    documents: [
      {
        source: 'aadhaar',
        label: 'Synthetic identity record',
        issuer: 'Local demo wallet',
        provenance: 'issued',
        state: 'available',
        issuedOn: '4 February 2024',
        digilockerUrl,
      },
      {
        source: 'marksheet12',
        label: 'Synthetic Class 12 marksheet',
        issuer: 'Demo Education Board',
        provenance: 'issued',
        state: 'available',
        issuedOn: '18 May 2022',
        digilockerUrl,
      },
      {
        source: 'bank',
        label: 'Synthetic bank account proof',
        issuer: 'Demo Bank',
        provenance: 'issued',
        state: 'available',
        issuedOn: '12 September 2025',
        digilockerUrl,
      },
      {
        source: 'incomeCertificate',
        label: 'Synthetic income certificate',
        issuer: 'Demo Revenue Office',
        provenance: 'uploaded',
        state: 'available',
        issuedOn: '10 February 2026',
        validUntil: '9 February 2027',
        digilockerUrl,
      },
      {
        source: 'casteCertificate',
        label: 'Synthetic category certificate',
        issuer: 'Demo Revenue Office',
        provenance: 'uploaded',
        state: 'applied',
        issuedOn: 'Applied 21 August 2026',
        digilockerUrl,
      },
    ],
  },
];

validateCitationSources(
  citizenProfiles.flatMap((profile) => [
    ...profile.issues.map((issue) => ({ id: `issue.${issue.id}`, source: issue.source })),
    ...profile.records.map((record) => ({ id: `record.${profile.id}.${record.id}`, source: record.source })),
  ]),
);

export function getCitizenProfile(id?: string | null): CitizenProfile {
  return citizenProfiles.find((profile) => profile.id === id) ?? citizenProfiles[0];
}
